//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analyzer1 {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Analyzer1.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity class should have the &apos;DataContract&apos; attribute.
        /// </summary>
        internal static string AnalyzerAttributeDescription {
            get {
                return ResourceManager.GetString("AnalyzerAttributeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name &apos;{0}&apos; should have the &apos;DataContract&apos; attribute.
        /// </summary>
        internal static string AnalyzerAttributeMessageFormat {
            get {
                return ResourceManager.GetString("AnalyzerAttributeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity class should have the &apos;DataContract&apos; attribute.
        /// </summary>
        internal static string AnalyzerAttributeTitle {
            get {
                return ResourceManager.GetString("AnalyzerAttributeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity class should be public.
        /// </summary>
        internal static string AnalyzerPublicClassDescription {
            get {
                return ResourceManager.GetString("AnalyzerPublicClassDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name &apos;{0}&apos; should have the &apos;public&apos; modificator.
        /// </summary>
        internal static string AnalyzerPublicClassMessageFormat {
            get {
                return ResourceManager.GetString("AnalyzerPublicClassMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity class should be public.
        /// </summary>
        internal static string AnalyzerPublicClassTitle {
            get {
                return ResourceManager.GetString("AnalyzerPublicClassTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required properties should be public.
        /// </summary>
        internal static string AnalyzerPublicPropertiesDescription {
            get {
                return ResourceManager.GetString("AnalyzerPublicPropertiesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; should have the &apos;public&apos; modificator.
        /// </summary>
        internal static string AnalyzerPublicPropertiesMessageFormat {
            get {
                return ResourceManager.GetString("AnalyzerPublicPropertiesMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required properties should be public.
        /// </summary>
        internal static string AnalyzerPublicPropertiesTitle {
            get {
                return ResourceManager.GetString("AnalyzerPublicPropertiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity class should have required properties.
        /// </summary>
        internal static string AnalyzerRequiredPropertiesDescription {
            get {
                return ResourceManager.GetString("AnalyzerRequiredPropertiesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity should have the {0} property.
        /// </summary>
        internal static string AnalyzerRequiredPropertiesMessageFormat {
            get {
                return ResourceManager.GetString("AnalyzerRequiredPropertiesMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity class should have required properties.
        /// </summary>
        internal static string AnalyzerRequiredPropertiesTitle {
            get {
                return ResourceManager.GetString("AnalyzerRequiredPropertiesTitle", resourceCulture);
            }
        }
    }
}
